---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.1-bullseye

inputs:
  - name: dp-frontend-filter-flex-dataset

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-frontend-filter-flex-dataset/ci/scripts/build.sh
